# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 710ee4ee15d24b0f3e7b085305f94e314d5b4271676ee127d862cf3488c0620e40f0d316c9d39f8dd668f1d88a0a1e75c24bac3609f7e64e4f4c4d7131cb8482

test:
  secret_key_base: 2533f5d7e16487a12f3863c4d26b1e8babf690d0c814117d6d510df18d7c668569bf1cd83ee8e56b34e2522054011e005542e7ff5b7c0212d302fffae248e360

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
